// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkkknvcqyybbznhbyprd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJra2tudmNxeXliYnpuaGJ5cHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzM5NzUsImV4cCI6MjA1ODIwOTk3NX0.djcDdhiFopm8BtU1L7_nYjZYfMvKW6MWssj3S_gRNpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);